AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for SageMaker Notebook Instance with S3 and SSM Parameter Store'

Parameters:
  NotebookInstanceName:
    Type: String
    Description: Name of the SageMaker Notebook Instance
  S3BucketName:
    Type: String
    Description: Name of the S3 Bucket for SageMaker
  SSMParameterName:
    Type: String
    Description: Name of the SSM Parameter Store variable

Resources:
  SageMakerNotebookInstanceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [sagemaker.amazonaws.com]
            Action: ['sts:AssumeRole']
      Policies:
        - PolicyName: SageMakerAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:DeleteObject'
                  - 's3:ListBucket'
                Resource:
                  - !Sub 'arn:aws:s3:::${S3BucketName}/*'
                  - !Sub 'arn:aws:s3:::${S3BucketName}'
              - Effect: Allow
                Action:
                  - 'ssm:GetParameter'
                  - 'ssm:PutParameter'
                Resource:
                  - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${SSMParameterName}'

  SageMakerNotebookInstance:
    Type: 'AWS::SageMaker::NotebookInstance'
    Properties:
      InstanceType: ml.t2.medium
      RoleArn: !GetAtt SageMakerNotebookInstanceRole.Arn
      NotebookInstanceName: !Ref NotebookInstanceName

  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref S3BucketName

  SSMParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: !Ref SSMParameterName
      Type: String
      Value: 'InitialValue'

Outputs:
  NotebookInstanceUrl:
    Description: URL of the SageMaker Notebook Instance
    Value: !Sub 'https://${AWS::Region}.console.aws.amazon.com/sagemaker/home?region=${AWS::Region}#/notebook-instances/openNotebook/${NotebookInstanceName}'
  S3BucketName:
    Description: Name of the S3 Bucket
    Value: !Ref S3BucketName
  SSMParameterName:
    Description: Name of the SSM Parameter
    Value: !Ref SSMParameterName
